### ISSUE TITLE
Origin of third party libraries is not clear

### ISSUE THREAD

**Issue by gadostal-swordfish** [mpromonet/webrtc-streamer-html#3]
Hi,

We try to make sure that we use source code that is licensed appropriately to make sure we take care of open source developers. It isn't clear what the origin of some of the *.js files in libs is.

It would be great to add a README to indicate where the *.js files came from. This would also help if newer versions could be used.

Specifically I'm unsure about /libs/request.min.js

Thanks,

Geordie

**Comment by mpromonet** [comment]
Hi,

It is embeded to simplify deployment on isolated network, but you can use from a cdn.

For instance https://cdnjs.cloudflare.com/ajax/libs/request/2.88.2/request.min.js

Best Regards,
Michel.
